### ISSUE TITLE
Maximum order for `drjit.sh_eval`

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#104]
The `order` parameter of [`drjit.sh_eval`](https://drjit.readthedocs.io/en/latest/reference.html#drjit.sh_eval) is limited to 10. I guess the reason is that the [code](https://github.com/mitsuba-renderer/drjit/blob/master/include/drjit/sh.h) becomes increasingly verbose for higher orders, because the parameters are basically hard-coded. Would it be interesting to you to add a version, which calculates the parameters of higher orders on-the-fly? I'd like to come up with a PR, but I'm afraid I lack the required skills.

**Comment by Speierers** [comment]
Indeed it would be great to be able to compute higher-order coefficients. Unfortunately, we won't have time to look into this in the near future. If you take a stab at this, a PR would be greatly appreciated as always ;)
