### ISSUE TITLE
Question about `drjit::Array`

### ISSUE THREAD

**Issue by samuelpmish** [mitsuba-renderer/drjit#109]
Hi,

I'm porting some existing simulation code to enoki / `drjit::Array`s and some of the original code uses `bool` to `double` conversions to implement piecewise functions in a branchless way, 

```cpp
double foo(double x) {
  return (x > 0) * 4 + sin(2 * x);
}
```

when moving this code to `drjit::Array`, it fails because there is no way to convert the mask to a `drjit::Array`

```cpp
using namespace drjit;
using double8 = drjit::Array<double, 8>;

double8 foo(double8 x) {
  return (x > 0) * 4 + sin(x);
  //     ^^^^^^^
  // error: no viable conversion from returned value of type 
  // 'drjit::Mask<double, 8>' to function return type 'double8' (aka 'Array<double, 8>')
}
```

One way to address this would be to manually transform the entire codebase to adopt `drjit::select( ... )`, or `drjit::masked( ... )` where appropriate.

My question is: would it make sense to define this kind of `drjit::Mask` -> `drjit::Array` conversion (or some basic arithmetic operations between masks and arrays), so that `drjit::Array` could support this kind of branchless pattern? The potential benefit is that more regular C++ code would be directly compatible with `drjit::Array` without modification.

**Comment by wjakob** [comment]
Hi @samuelpmish  -- please use `dr::select` for this. Masks are quite special representations in some of the backends and the cast will invariably require a special operation. `dr::select` is is the safe way to express the intent of the cast. The underlying compiler (GCC, Clang, or the JIT-ed backends) will still do further optimizations, so I don't think you are losing anything.
