### ISSUE TITLE
DrJit crashes when running with multiprocess

### ISSUE THREAD

**Issue by bathal1** [mitsuba-renderer/drjit#116]
When using `multiprocessing` to run a function using DrJit to perform some computation on the GPU in a separate process, the process crashes with the following error: 

```bash
Critical Dr.Jit compiler failure: cuda_check(): API error 0003 (CUDA_ERROR_NOT_INITIALIZED): "initialization error" in /home/bnicolet/Documents/code/mitsuba3-diff_cv/ext/drjit/ext/drjit-core/src/cuda_api.h:188.
```

Note that this does not happen if the process is spawned by `subprocess` instead of `multiprocessing`.

Here is a minimal reproducer: 

```python
import drjit as dr
from multiprocessing import Process

def task():
    a = dr.cuda.Float(1, 2, 3)
    print(a)

process = Process(target=task)

# Runs the process in the main thread, works
process.run()

# Runs the process in a separate process, crashes
process.start()
```

Info 
-----
DrJIT version: `master/fd3685091fc7a7c39bc288ddd96f183898371931`
GPU: NVIDIA RTX 3080Ti
OS: Ubuntu 22.04

**Comment by wjakob** [comment]
This is likely relevant: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods.

Spawning new processes using *fork* is not going to work for a CUDA application.

Does
```
multiprocessing.set_start_method('spawn')
```
help?

**Comment by bathal1** [comment]
Yes, that works, thanks !

**Comment by wjakob** [comment]
Great!
