### ISSUE TITLE
How to convert a drjit.llvm.ad.Int to a Python built-in int in the eval loop?

### ISSUE THREAD

**Issue by Theo-Wu** [mitsuba-renderer/drjit#118]
In the eval function of BSDF, I want to use a `drjit.llvm.ad.Int` as an index for slicing a list. I tried to convert it into a python built-in `int`,  for example,
```
a = mi.Point2i(1,2)
index = a.x[0]
```
or
```
a = mi.Point2i(1,2)
index = np.array(a.x).squeeze()
```
but I got the errors:
```
jitc_var_schedule(r1322138): placeholder variables are used to record computation symbolically
and cannot be scheduled for evaluation! This error message could appear for
the following reasons:

1. You are using DrJit's loop or virtual function call recording feature
   and tried to perform an operation that is not permitted in this restricted
   execution mode. Please see the documentation of recorded loops/virtual
   function calls to learn about these restrictions.

2. You are accessing a variable that was modified as part of a recorded
   loop and forgot to specify it as a loop variable. Please see the
   drjit::Loop documentation for details.
```

Can I get some suggestions about how to achieve that? Thank you.

**Comment by wjakob** [comment]
Mitsuba records virtual function calls symbolically (with placeholder values) to build a megakernel-- you aren't allowed to peek into function arguments, print them, or construct numpy arrays from them.

You can call

```
dr.set_flag(dr.JitFlag.VCallRecord, False)
dr.set_flag(dr.JitFlag.LoopRecord, False)
```
at the beginning of the program to turn off all symbolic features, though this will come at a significant computation + memory overhead.

**Comment by Theo-Wu** [comment]
Thank you! It's helpful.
