### ISSUE TITLE
Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#120]
Hey! I recently updated `mitsuba` and `drjit` to the most recent master version (compiled myself) and ran into the following issue:

```
Critical Dr.Jit compiler failure: cuda_check(): API error 0700 (CUDA_ERROR_ILLEGAL_ADDRESS): "an illegal memory access was encountered" in /src/mitsuba3/ext/drjit/ext/drjit-core/src/util.cpp:203.
Aborted (core dumped)
```

Unfortunately, my project is rather large, so before I try to come up with a minimal reproduction, I was wondering if the error alone might suffice to identify the problem.

Of course, I’ll be more than happy to provide any additional information that is required.

Thanks!

**Comment by wjakob** [comment]
Sorry, this will not be enough to identify the problem.

**Comment by maxfrei750** [comment]
Thanks for the swift reply! I thought so. Do you think that a debug log might suffice, or is the error too generic?

**Comment by wjakob** [comment]
Far too generic, we'll need a reproducer.

**Comment by maxfrei750** [comment]
I'll try my best. Thanks!

**Comment by maxfrei750** [comment]
I'm afraid, I don't have the time right now to create a reproducer, so closing for now. Thanks for taking your time.
