### ISSUE TITLE
`dlpack` failing on unit dimensions

### ISSUE THREAD

**Issue by merlinND** [mitsuba-renderer/drjit#122]
Hello!

I'm encountering an issue with DrJit's stride specification in the DLPack interface, when the tensor has dimensions of size 1:

```python
import drjit as dr
import numpy as np
import tensorflow

print('DrJit version:', dr.__version__)
print('TensorFlow version:', tensorflow.__version__)
print('')

a = dr.cuda.TensorXf(dr.arange(dr.cuda.Float32, 3*4), shape=(1, 3, 1, 4, 1))
print('DrJit:', a, dr.shape(a))
print(a.array)
print('----\n')

b = a.tf()
print('TF:', b.shape, b.numpy().shape)
print(b)
```

Output:
```
DrJit: TensorXf(shape=(1, 3, 1, 4, 1)) (1, 3, 1, 4, 1)
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]
----

shape: (1, 3, 1, 4, 1)
stride: (0, 4, 0, 1, 0)
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    b = a.tf()
  File "venv/lib/python3.10/site-packages/drjit/generic.py", line 1674, in tf
    return from_dlpack(a.__dlpack__())
  File ".venv/lib/python3.10/site-packages/tensorflow/python/dlpack/dlpack.py", line 63, in from_dlpack
    return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid strides array from DLPack
```

PyTorch and Numpy accept the conversion without issue, but it might be due to a missing check on the strides.

---

The `shape` and `stride` prints were added to `op_dlpack`:

https://github.com/mitsuba-renderer/drjit/blob/29edaf20856d0e2919ba80be6816da9b0566164c/drjit/generic.py#L1637-L1648

The problem seems related to these lines in `export_()`:

https://github.com/mitsuba-renderer/drjit/blob/29edaf20856d0e2919ba80be6816da9b0566164c/drjit/generic.py#L1567-L1569

Commenting them out fixes the problem and the unit tests still pass. They were introduced together with a fix related to matrices, so I'm not sure if there are any other consequences.
As far as I can tell, commenting these lines out would match e.g. the NumPy implementation of the protocol: https://github.com/numpy/numpy/blob/340b3ff2ea6fdfebcb43a83aa8799dffd77ab325/numpy/core/src/multiarray/dlpack.c#L249-L255

**Comment by njroussel** [comment]
Hi @merlinND :smile: 

I've looked at different implementations and the DLPack documentation, I feel like this is a bit aggressive on Tensorflow's side. 
Whether the stride should be 0 or 1 for a unit dimension doesn't really matter when indexing, but Tensorflow does indeed have a [sanity check which requires it to be 1](https://github.com/tensorflow/tensorflow/blob/f1962819939849fa16b431fd666e460b921d917a/tensorflow/c/eager/dlpack.cc#L261).

I would be in favor in removing these three lines. @wjakob was there a specific reason why these were added?

**Comment by njroussel** [comment]
Update:
These lines were specifically for `numpy` apparently. I've read through both their `dlpack` and `array_interface` implementations, neither seem to require a stride of 0. 
I've pushed a patch to `master` with a couple new tests: https://github.com/mitsuba-renderer/drjit/commit/0220699e3a87847c5507e902a124090ab98c8aee

Thanks for the bug report :)
