### ISSUE TITLE
Compiling with clang 15

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#126]
I'm compiling on Ubuntu 22.04, which usually features clang 14.0.0. When trying to compile, drjit graciously informed me that I need a higher (or lower) clang version and even where to find it (https://apt.llvm.org/). Very helpful! Unfortunately, the custom repo for clang 14 is apparently no longer maintained. Therefore, I tried to resort to clang 15. It compiles just fine, but it crashes with segfaults. So I just wanted to ask, if clang 15 has ever been tested or if I should try to find another solution, e.g. waiting for drjit to be updated in the mitsuba repo and reverting to clang 11. Thanks!

**Comment by njroussel** [comment]
I just gave clang-15 a try, everything seems to be working fine (I ran our mitsuba test suite). Could you provide a reproducer?

The `llvm.sh` script (documented on  https://apt.llvm.org/ still) still works for older versions.

**Comment by maxfrei750** [comment]
> The llvm.sh script (documented on https://apt.llvm.org/ still) still works for older versions even though they might not be listed -- I installed v14.0.6 on Ubuntu 20.04.

Neat! Thanks for the tip.

The following code results in a segmentation fault, _but not_ if I use VSCode's debugging function:

```
import drjit as dr
import torch

# Start with a Dr.Jit tensor
a = dr.llvm.ad.TensorXf([1, 2, 3], shape=[3])
dr.enable_grad(a)

# Some Dr.Jit arithmetic
b = dr.sin(a)


# Wrap a function performing some arithmetic using PyTorch
@dr.wrap_ad(source='drjit', target='torch')
def torch_func(x):
    return torch.cos(x) + torch.sin(x)


# Excecute the wrapped function (returns a Dr.Jit tensor)
c = torch_func(b)

# Some more Dr.Jit arithmetic
d = dr.tan(c)

# Propagate gradients to variable a (through Dr.Jit -> PyTorch -> Dr.Jit)
dr.backward(d)

# Inspect the resulting gradients
print(dr.grad(a))
print("Success")
```

**Comment by njroussel** [comment]
I've been using clang-15 for at least 3 months without any issues.

However, your reproducer still segfaults (even with older versions of LLVM). This is some dynamic linkage problem because Pytorch spills all its symbols in the global namespace. **Swapping the order of imports fixes this.**
There are hundreds of issues like this on the PyTorch tracker, hopefully they'll solve it...

**Comment by maxfrei750** [comment]
@njroussel Thanks for addressing this issue and providing a workaround. I just re-tested the code that I posted above and interestingly enough, it did no longer produce a segfault, no matter how I ordered the imports.

**Comment by njroussel** [comment]
:exploding_head: 

I believe this was specifically an issue on Linux when building with Clang - other platforms/compilers have a different behavior in their dynamic loaders. Is this not the case for you @maxfrei750 ?

**Comment by lkskstlr** [comment]
As an additional data point: I just came across this issue with clang `15.0.7` on Ubuntu `22.04` when building d74f55939954a4b99f37f4021e29327aacd5a75c (v0.4.2). It does not happen with v0.4.2 installed via pip, when running with attached debugger, or in a jupyter notebook.
