### ISSUE TITLE
Accessing array items with loop variable as index in function

### ISSUE THREAD

**Issue by Linyou** [mitsuba-renderer/drjit#139]
Hello,

I am trying to access array items with a loop variable as index in a function, but I am not sure if this is possible. Here's the code I have currently:

```python
def kernel(xyzs: Array3f, sigmas: Array1f, step: Array1i):
    result = Array3f(0)
    i = UInt32(0)
    active = Bool(True)
    loop = Loop("Step", lambda: (result, i, step, active))
    while loop(active):
        sigma = sigmas.__getitem__(i) # __getitem__ dose work!
        active = i < step
        result += xyzs + sigma
        i += 1

    return result

x = dr.linspace(Float, -1, 1, 100)
x, y, z = dr.meshgrid(x, x, x)
xyz = Array3f(x, y, z)
sigmas = dr.ones(Array1f, shape=(1000000*2))
step = dr.ones(Array1i, shape=(1000000))*2
kernel(xyz, sigmas, step)
```

I want the `kernel` function to run in parallel on the `xyz` array and access the `sigmas` array with an index that is computed during runtime. Please note that the `xyz` and `sigmas` arrays have different shapes. Is there a way to achieve this? Any help would be appreciated.

Thank you!

**Comment by dvicini** [comment]
You will want to use [dr.gather](https://drjit.readthedocs.io/en/latest/reference.html#drjit.gather). That's the drjit indexing operation and is compatible with the loop construct.

**Comment by Linyou** [comment]
Thanks!
