### ISSUE TITLE
Cumulative operator

### ISSUE THREAD

**Issue by Linyou** [mitsuba-renderer/drjit#141]
Hi!

Do we have cumulative operators like `cumsum` in Drjit ? I could not find anything in the documentation. If not, is there any alternative way to implement such operator in Drjit?

Thanks!

**Comment by njroussel** [comment]
Hi @Linyou 

We haven't implemented any cumulative operations, we only have support for reductions. Something like `cumsum` should just be a few lines of python. 

Unless you're looking for something super efficient (which I'm not even sure is possible), this would require some more work.

**Comment by Linyou** [comment]
Thanks for the reply!

**Comment by wjakob** [comment]
There is a prefix sum for 1D arrays (`uint32_t` only) implemented in drjit-core. It should be easy to extend it to other types like `float` and expose it in Python (at least for pure 1D arrays). But it is not on our own priority list, so help is appreciated.
