### ISSUE TITLE
Failed to import drjit

### ISSUE THREAD

**Issue by owaranainatsu** [mitsuba-renderer/drjit#147]
Error message:

> error 11:03:04.926: Disposing session as kernel process died ExitCode: undefined, Reason: /home/arrow/anaconda3/envs/mitsuba3/lib/python3.9/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/arrow/anaconda3/envs/mitsuba3/lib/python3.9/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7790baf4-73dc-4fee-912d-0537ace06fde' instead of 'b"7790baf4-73dc-4fee-912d-0537ace06fde"'.
  warn(
info 11:03:04.926: Dispose Kernel process 30600.
error 11:03:04.927: Raw kernel process exited code: undefined

Suddenly I cannot import drjit today, and I tried to update and reinstall traitlets but it didn't work.

**Comment by njroussel** [comment]
Hi @owaranainatsu 

This seems unrelated to DrJit, `traitlets` is not a dependency of `drjit`. Additionally, these are just warnings as far as I can tell.
