### ISSUE TITLE
[Question] Does Dr.JIT support median or percentile-like functionality?

### ISSUE THREAD

**Issue by costrice** [mitsuba-renderer/drjit#157]
I wanted to compute the median of an array, but failed to find a function in `drjit` that does this job.

Is this deliberately designed, for performance considerations like "the median operation can not be easily parallelized, thus it is not encouraged to compute the median"?

**Comment by njroussel** [comment]
Hi @costrice 

No, DrJit does indeed not have such operations.

As for the reasoning, it might also just be because we never had a need for these operations. They are also relatively difficult to implement efficiently as you mentioned.
