### ISSUE TITLE
Example project of Binding C++ code?

### ISSUE THREAD

**Issue by 111116** [mitsuba-renderer/drjit#158]
Hi, I'm looking for an example build system that binds C++ code that operates on `dr::Array`, and create a Python interface. There used to be a link to https://github.com/wjakob/dr_python_test which expires. I'd appreciate such example, or any help because I was struggling to get a working build system. Thanks!

**Comment by dvicini** [comment]
Hi,

Maybe there is an example I am not aware of, but I went through this process with the following package:
https://github.com/rgl-epfl/fastsweep

This uses both C++ and Python DrJit and compiles into a package that can be pip-installed. Not that the version of this package needs to remain consistent with DrJit to ensure interoperability. It also needs to be compiled with the same compiler and settings (e.g., compiling `fastsweep` locally will be incompatible with the pip-installed drjit version)

**Comment by njroussel** [comment]
Hi @111116 

Indeed, I think the `fastsweep` project is the best/smallest project we have at this time.
Once you have setup your build system, feel free to share it here if you think it can help out others :+1:
