### ISSUE TITLE
Is the location of the kernel cache controllable?

### ISSUE THREAD

**Issue by errissa** [mitsuba-renderer/drjit#162]
Is there some way to change the location that DrJIT uses to cache compiled kernels from ~/.drjit to something user configurable?

**Comment by njroussel** [comment]
Hi @errissa 

This is not something that is currently supported.
If you wish to implement this yourself, [here](https://github.com/mitsuba-renderer/drjit-core/blob/master/src/init.cpp#L86-L93) is where this path is initialized. We'd welcome a PR on this.
