### ISSUE TITLE
autodiff not_

### ISSUE THREAD

**Issue by PieterPeers** [mitsuba-renderer/drjit#167]
This is minor, but I believe that not_ in autodiff.h (line 1088) should be (at least for the 'scalar' backbone; not sure for other backbones)

`return DiffArray::create(0, !m_value);`

instead of:

`return DiffArray::create(0, ~m_value);`

Example:

`std::cerr << !(drjit::mask_t<float>(true)) << " vs. " << !(drjit::mask_t<drjit::DiffArray<float>>(true)) << std::endl;`

incorrectly produces "0 vs [1]" using clang 16.

**Comment by njroussel** [comment]
Hi @PieterPeers 

Thanks for reporting this, I pushed a fix in https://github.com/mitsuba-renderer/drjit/commit/faa3633c3e4609e3e154d352bb2351de93770770
