### ISSUE TITLE
pow with negative arguments

### ISSUE THREAD

**Issue by PieterPeers** [mitsuba-renderer/drjit#168]
It am getting incorrect results with pow when the argument is negative and the exponent is 2.0 (with scalar backbone); it seems that the fallback option is taken (exp2(log2)) which correctly does not handle negative numbers (using clang 16).

Example:
`std::cerr << drjit::pow( -0.5, 2.0) << std::endl;     // prints 0`
`std::cerr << drjit::pow( drjit::Array<double, 3>(-0.5), 2.0) << std::endl;   // prints [-nan, -nan, -nan]`
`std::cerr << drjit::pow( drjit::Array<double, 1>(-0.5), 2.0) << std::endl;   // ptints 0 (or sometimes 6.92522e-310)`
`std::cerr << std::pow( -0.5, 2.0) << std::endl;   // correct result 0.25`

The issue seems to be the constexpr condition on line 998 in math.h.  Perhaps the `is_dynamic_v<X>` should be dropped?

**Comment by wjakob** [comment]
Just double-checking: does this change mean that we're losing an important optimization in JIT modes? (where I believe is_dynamic_v is true). In Python, it's quite common to use `**` extensively even for basic stuff like squaring an array. The transcendental implementation of `pow` via exp/log would have severe overheads in that case.

**Comment by njroussel** [comment]
No, the code path for JIT modes doesn't change. It only changes the behaviour of a `pow` operation with a scalar or non-JIT array basis operand.

**Comment by wjakob** [comment]
ok, all good then!
