### ISSUE TITLE
ScalarTransform4f to numpy/torch

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/drjit#170]
Is there anyway to convert a transform matrix to numpy?
like
`rot = T.rotate([0,1,0], 90)`
`rot.numpy()`

**Comment by merlinND** [comment]
Hello @andyyankai,

You can get the underlying transformation matrix in NumPy or Torch as follows:

```
rot.matrix.numpy()
rot.matrix.torch()
```
