### ISSUE TITLE
Random assertion error: queue.cpp:354

### ISSUE THREAD

**Issue by sagesimhon** [mitsuba-renderer/drjit#180]
Hi, 

I am running various rendering jobs via mitsuba 3 and the process throws an assertion error, and a core dump, at random times in my processing stack on a linux machine with a large number of CPUs (this never happens when running identical code on a Mac).

"Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1"

I have no clue to what the cause of this issues is. Any ideas where to start?

**Comment by njroussel** [comment]
Hi @sagesimhon 

This is an assertion in our thread/worker pool job submission system. It's typically indicative of some race condition in higher-level code.
Are you using a _vanilla_ build of Mitsuba/Dr.Jit? These type of issues are hard to track down and fix without a consistent reproducer.

**Comment by dvicini** [comment]
I also at some point ran into this a few months ago, but I don't recall what caused it or how I got rid of this problem (hopefully?), and I don't have a reproducer either.

**Comment by sagesimhon** [comment]
yes, it's quite random, it seems to happen more frequently with higher cpus. I am using vanilla build, via conda install. Any suggestions where to start to get more debugging info on the root cause, or at least print the stack trace?

**Comment by sagesimhon** [comment]
tried: 

mitsuba: 3.30
drjit:  0.4.2

and 
mitsuba-3.2.1
drjit-0.4.1 

both fail.

with libLLVM-15.so

**Comment by njroussel** [comment]
Let me close this, to keep this tidy.

Anyone who finds this issue, we're tracking it over here: https://github.com/mitsuba-renderer/mitsuba3/issues/849
