### ISSUE TITLE
Missing definition of mulhi_scalar()

### ISSUE THREAD

**Issue by jeongseok-meta** [mitsuba-renderer/drjit#188]
The function `mulhi_scalar()` is called within `array_utils.h`, but it seems not defined in drjit:

https://github.com/mitsuba-renderer/drjit/blob/c71ebb792c88abf2460e296e213cbcb8069388a8/include/drjit/array_utils.h#L293

which was previously defined in Enoki's [array_fallbacks.h](https://github.com/mitsuba-renderer/enoki/blob/2a18afa2402e0677887c8439fa3d6a270ea15726/include/enoki/array_fallbacks.h#l339-L383).

Is the omission of this function's definition in drjit intentional? If so, could you provide insights on how to address calls to this function? If not, are there plans to integrate this function into the drjit repository?

**Comment by njroussel** [comment]
Fixed in #189
