### ISSUE TITLE
DrJit compiler failure： DrJit has created more than 4 bilion variables

### ISSUE THREAD

**Issue by joyDeng** [mitsuba-renderer/drjit#192]
When I try to render a 64spp scene for 500 frames, drjit keeps giving me the following error message, I tried to use drjit.eval(img) to force the evaluation, but this doesn't help. This problem also happens with my optimization, I can't really go beyond 1500 iterations.

Critical Dr.Jit compiler failure: DrJit has created more than 2^32 (4 billion) variables, which is currently the limit. Bug Wenzel to fix this (it will involve sorting scheduled variables by scope ID instead of variable ID and making the counter big enough that it will never overflow..).

**Comment by njroussel** [comment]
Hi @joyDeng 

This limitation was lifted almost a year ago in this PR: https://github.com/mitsuba-renderer/drjit-core/pull/41.

I recommend upgrading to a newer version of Dr.Jit :smile:
