### ISSUE TITLE
Is array of references no longer possible?

### ISSUE THREAD

**Issue by YunHsiao** [mitsuba-renderer/drjit#201]
By requiring array element types to be default constructible, references are no longer a valid array element type:

```cpp
using FloatP = Packet<float, 8>;

FloatP a, b, c; // Generated from different structures

Array<const FloatP&, 3> v{a, b, c}; // Error: Type underlying drjit::Array must be default-constructible!
```

Is there any workarounds for making a vector made of references without copying?

**Comment by rtabbara** [comment]
Hi @YunHsiao ,

If you knew ahead of time the final array size you could go the other way and pre-allocate your array and reference the individual elements

```
using FloatP = Packet<float, 8>;

Array<FloatP, 3> v;
FloatP& a = v[0];
FloatP& b = v[1];
FloatP& c = v[2];
```

If that's perhaps a bit too unwieldy for your purposes I would say having an `Array<FloatP*, 3>` would be the way to go.

**Comment by YunHsiao** [comment]
Oh I just realized the data structure layout I use is is not quite right:

```cpp
using FloatP = Packet<float, 8>;
// Declare a custom struct using DRJIT_STRUCT infrastructures
using MyStructP = MyStruct<FloatP>;

using FloatX = DynamicArray<FloatP>;
using MyStructX_DoNotUse = MyStruct<FloatX>; // This techniquely works but will be very painful to use

using MyStructX = DynamicArray<MyStructP>; // Much better
```

Falls straight into the trap, haha. Closing this.
