### ISSUE TITLE
dr.linspace(mi.Float, -1,1,256) output single value

### ISSUE THREAD

**Issue by chaihahaha** [mitsuba-renderer/drjit#203]
mitsuba version: 3.4.0
drjit version: 0.4.3
os: windows x86_64

```python
import mitsuba as mi
import drjit as dr
mi.set_variant('scalar_rgb')
print(dr.linspace(mi.Float, -1, 1  256))
```
the output is a single value -1 instead of a vector.

**Comment by njroussel** [comment]
Hi @chaihahaha 

This is expected behavior. 
You can read more about it here: https://github.com/mitsuba-renderer/mitsuba3/issues/775
