### ISSUE TITLE
How to implement the join operation of two arrays in Drjit

### ISSUE THREAD

**Issue by linxxcad** [mitsuba-renderer/drjit#205]
I want to realize merge multiple arrays in type of Array3f.
A=Array3f( [0,1,2] )
B=Array3f( [3,4,5] )
C=Array3f( [6,7,8] )
How to get D=Array3f( [
 [0,1,2] , [3,4,5] , [6,7,8]
])

It can be done in numpy by append or stack.
Is this operation differentiable?

I would appreciate it if anyone could help me

**Comment by rtabbara** [comment]
Hi @linxxcad,

I think one approach could be to use `dr.ravel/dr.unravel`

```python
# Flatten the input
z = Float(dr.ravel([A,B,C]))

# Use row-major ordering to repackage the Array3f
D = dr.unravel(Array3f, z, order='C')
```
And yes, this will still be differentiable
