### ISSUE TITLE
module 'drjit' has no attribute 'hint'

### ISSUE THREAD

**Issue by ioissss** [mitsuba-renderer/drjit#229]
I was able to find the drjit.hint function in the documentation, but when calling drjit.hint in code the compiler tells me: module 'drjit' has no attribute 'hint'

“”“”
while dr.hint(active,max_iterations = max_depth,label="path tracer written by zdq"):
“”“

![image](https://github.com/mitsuba-renderer/drjit/assets/91249397/68efb008-2d40-42b5-9128-45b643b72387)

**Comment by njroussel** [comment]
Hi @ioissss 

We're undergoing a large change currently, please be careful when refering to the online documentation.
Use the most recent released versions:
* Drjit: https://drjit.readthedocs.io/en/v0.4.6/
* Mitsuba: https://mitsuba.readthedocs.io/en/stable/

The `dr.hint` is a new feature which is available on `master` but not on any public PyPI release yet.
