### ISSUE TITLE
An error code but no exception is reported

### ISSUE THREAD

**Issue by ioissss** [mitsuba-renderer/drjit#231]
I've been doing some experiments with the mitsuba3 library, and when I include the statement `active_em &= (ds.pdf!=0)` in my code, it causes my code to fail to get results, but there are no runtime errors or exceptions. 

```
active_em = mi.Bool(True)
active_em &= (ds.pdf!=0)
```
Is there a problem with this usage and what are the alternatives?  I've tried this：
```
active_em = mi.Bool(True)
active_em &= (dr.select(ds.pdf != 0, True, False))
```
but it dose not work

**Comment by njroussel** [comment]
Hi @ioissss 

Vectorized equality and inequality comparisons should be done with `dr.eq(a, b)` and `dr.neq(a, b)` respectively. All other comparisons use the typical operands. 

This will be chaning in the next release where you'll able to use the `==` and `!=` operands as you have in your code snippet.
