### ISSUE TITLE
Bug report with slicing of ArrayXf

### ISSUE THREAD

**Issue by XiaoXinyyx** [mitsuba-renderer/drjit#284]
Read and Write inconsistency :

```py
import drjit as dr
a = dr.cuda.ad.ArrayXf([1,2,3],[4,5,6])
a
# [[1.0, 4.0],
#  [2.0, 5.0],
#  [3.0, 6.0]]

a[:,0]
#[1.0, 2.0, 3.0]

a[:,0] = 10
# [[10.0, 10.0],
#  [2.0, 5.0],
#  [3.0, 6.0]]
```

**Comment by wjakob** [comment]
`Array*` types don't support the general slicing protocols and generally cannot be used like tensors. What you need to use is some form of `TensorX*`. That said, I think that this should fail with a proper error message.
