### ISSUE TITLE
The docstr.rst file contains some Unicode characters that may cause a runtime crash.

### ISSUE THREAD

**Issue by zhongsitang** [mitsuba-renderer/drjit#315]
My development environment is Windows11 Simplified Chinese version, python version 3.11, Visual Sutdio 2022
Python crashed when import drjit. After debugging, it was found that the docstr file ``` src\python\docstr.rst ``` contains serveral unicode character ```↵```, which may cause crash when initialize the ```nanobind::str``` object.
## example 
Lines 2682-2684  of ``` src\python\docstr.rst ```:
``` 
>>> dr.gather(dtype=UInt, source=UInt(1, 2, 3), index=UInt(0, 1, 100))
drjit.gather(): out-of-bounds read from position 100 in an array↵
of size 3. (<stdin>:2)
```
The code in line 165 of ```ext\nanobind\src\nb_enum.cpp``` will cause crash
```
el.attr("__doc__") = doc ? str(doc) : none();
```
Any non-ASCII character will crash because of this, is it a bug?

**Comment by wjakob** [comment]
So weird, this doesn't make much sense to me. Those characters are valid unicode, and Python should be able to convert them. Are you compiling Mitsuba/Dr.Jit yourself? If so, could you try adding `PyUnicode_FromString(doc); PyErr_Print();` on the line above to try to get an error message from Python?
Thanks!

**Comment by zhongsitang** [comment]
Yes, I'm compliling Dr.Jit myself. The error message printed is: 
```
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1297-1298: invalid continuation byte. 
```
I found that the cause is that the MSVC compiler is defaulting to my system's encoding (GBK) rather than the correct encoding (UTF-8). This issue can be resolved by specifying the encoding during compilation. For example, by adding the following in CMake:
```
add_compile_options("/execution-charset:utf-8")
```
This problem only occurs on operating systems with specific locales, but it can lead to a serious error where Mitsuba/Dr.Jit cannot be successfully compiled. Do you consider fixing this issue in the source code?

**Comment by wjakob** [comment]
Amazing, thanks for tracking that down. We should include this flag this in the Dr.Jit build system.

**Comment by rtabbara** [comment]
Thanks @zhongsitang ! I've pushed a fix for this into `master`
