### ISSUE TITLE
Unexpected behavior of drjit.shape

### ISSUE THREAD

**Issue by JamesZFS** [mitsuba-renderer/drjit#43]
I am playing with drjit in python and seem to find an undesirable behavior of the `shape` function in `router.py`:
If you define a ragged 2D array whose # entries of the second dimension decrease, the output of `dr.shape` is None, which is the expected result of ragged arrays.
```python
a = mi.Color3f([0, 1, 2], [0, 1], [0, 1])
dr.shape(a)
```
out:
```
None
```
But if you define it in a way where # entries of the second dimension increase, the output is not None, but instead behave like the array is extended to a uniform-length array
```python
a = mi.Color3f([0, 1], [0, 1, 2], [0, 1, 2, 3])
dr.shape(a)
```
out:
```
[3, 4]
```

**Comment by Speierers** [comment]
This will be fixed in the next release: a026b56
