### ISSUE TITLE
Generate stubs

### ISSUE THREAD

**Issue by DoeringChristian** [mitsuba-renderer/drjit#48]
Since drjit loads its python functions into the __init__.py module, I'm not able to get linting and code completion to work.
Is it possible to generate stub files for drjit like they are for mitsuba3?

I'm currently trying to adapt mitsuba3's generate_stub_files.py to work for drjit so maybe I'll add a pull request when I got it working.

**Comment by dvicini** [comment]
I am closing this issue since we can discuss this in the pull request https://github.com/mitsuba-renderer/drjit/pull/49
