### ISSUE TITLE
Reading back to Scalar types floods cache dir with kernels

### ISSUE THREAD

**Issue by tszirr** [mitsuba-renderer/drjit#51]
Depending on how I read back values from wide device arrays to scalar arrays, I find a weird issue with unexpected kernel regeneration on every read: Using `.numpy()` to access values generates new kernels every time, whereas `dr.slice(...)` does not result in additional kernels (only one kernel cached in ~/.drjit).

Interestingly, this behavior is only observed for more complex types such as `Array3f`, `Matrix4f`, `Transform4f`, but not for `Float`. Are there some kind of uncached reshuffling kernels involved in the multi-dimensional `.numpy()` accessors?

# Repro

Tested on Ubuntu 20.04 LTS with Python 3.8:

```python
import drjit as dr
from drjit.scalar import Array3f as ScalarArray3f
from drjit.cuda.ad import Array3f

device = Array3f(3.0)

for i in range(100):
    host = ScalarArray3f(device.numpy()) # generates many kernels in ~/.drjit
    #host = ScalarArray3f(dr.slice(device)) # generates one kernel in ~/.drjit
    host[0] += i
    device.assign(host)

print(device)
```

**Comment by Speierers** [comment]
In your reproducer no kernels should be launched in the case of `dr.slice` as all your variables are literals. Note that you can increase the log level of DrJit to see when a kernel is launched:
```
dr.set_log_level(3)
```

Regarding `.numpy`, the data in `device` will first be linearized (e.g. using `dr.ravel`) which implies a couple `scatter`. The resulting array is then migratate to host memory (e.g. using `dr.migrate`) so this is all much more complicated than in the `dr.slice` case. You can take a look at the implementation of `export_` in `drjit/generic.py`.

Also note that `dr.slice` only fetches a single slice of a tensor, while `.numpy()` considers the whole array, so it is indeed migrating much more data from device to host.

Eventually this will all be improved once we have ported Mitsuba and DrJit to nanobind.

I will close this as it isn't really an issue.

**Comment by tszirr** [comment]
My original intention was to call `.numpy()` and not `dr.slice` for two reasons, one `dr.slice()` did not work reliably/without surprises with matrix types, as passing the result of `dr.slice()` to another matrix constructor transposes the matrix every time [1], and two I did want to have all the data transferred in the original use case.

The real thing I was looking for appears to be `dr.make_opaque`, which I recently found by means of other threads here (It seems very important for controllable JIT, but is currently missing in the documentation?):

```
import drjit as dr
from drjit.scalar import Matrix4f as ScalarMatrix4f
from drjit.cuda.ad import Matrix4f

device = Matrix4f(3.0)
for i in range(100):
    dr.make_opaque(device)
    host = ScalarMatrix4f(device.numpy())
    host[1][0] += i
    device.assign(host)
print(device)
```
Then it generates only a constant number of kernels and correctly prints:
```
[[[3.0, 4950.0, 0.0, 0.0],
  [0.0, 3.0, 0.0, 0.0],
  [0.0, 0.0, 3.0, 0.0],
  [0.0, 0.0, 0.0, 3.0]]]
```

Appendix regarding unexpected/inconvenient matrix transposition with `dr.slice`:
[1] This also generates a constant number of kernels but needs additional annoyance with knowing/fixing matrix layouts, the naive solution of using `dr.slice()` for opaque transfers computes the wrong result:
```
import drjit as dr
from drjit.scalar import Matrix4f as ScalarMatrix4f
from drjit.cuda.ad import Matrix4f

device = Matrix4f(3.0)
for i in range(100):
    host = ScalarMatrix4f(dr.slice(device))
    host[1][0] += i
    device.assign(host)
print(device)
```
in contrast to the expected result above prints:
```
[[[3.0, 2500.0, 0.0, 0.0],
  [2450.0, 3.0, 0.0, 0.0],
  [0.0, 0.0, 3.0, 0.0],
  [0.0, 0.0, 0.0, 3.0]]]
```

**Comment by wjakob** [comment]
One thing you have to keep in mind is that classes like `Matrix4f` are simply wrappers around `Float`-typed JIT variables. In other words, this all works very differently to PyTorch/Tensorflow/.., where a matrix or tensor wraps some region of memory. If you access one matrix entry after the other, Dr.Jit will compile a new kernel per evaluation (if it had not seen the expression tree associated with that specific `Float` variable before).

To avoid that, you can either ask Dr.Jit to evaluate all matrix entries in a single kernel and write 16 outputs (`dr.eval(my_matrix)`). Following that, accessing the matrix only does a `cudaMemcpy` from the device.

Alternatively, you can flatten the matrix using `dr.ravel`, which should produce a `Float` output variable with 16 entries. Accessing entries that variable will also launch a single kernel that computes its contents.

Does this clarify your question?

**Comment by tszirr** [comment]
My original issue mostly lies in controllability, my first few attempts all involved various variants of invoking `dr.eval()` in various locations, however, that always turned out a losing battle against special case-literal handling: Literals are not skipped in evaluation, meaning that even when I drop in `dr.eval()` before calling into any frequently used JITed function, it does not prevent drjit from generating N kernels for N different literals. The only reliable solution to guard against this so far has turned out to be `dr.make_opaque()`, which luckily forces even literals to be materialized into actual GPU buffers by means of calling `data()`/`jitc_var_eval_literal()` internally, for which I did not see a more idiomatic high-level API so far.

**Comment by tszirr** [comment]
Here are the code paths that I think are responsible for my issues, both `eval` and `schedule` actively exclude literals from evaluation/materialization, preventing them to act as a general and robust firewall against kernel floods:
https://github.com/mitsuba-renderer/drjit-core/blob/79a86c49abdf24d3a7d2a23e3f79aab1f76ea5f9/src/var.cpp#L864
https://github.com/mitsuba-renderer/drjit-core/blob/79a86c49abdf24d3a7d2a23e3f79aab1f76ea5f9/src/var.cpp#L809

**Comment by Speierers** [comment]
@tszirr note that it is also possible to use`dr.opaque(dtype, value, size)`. It works like `dr.full(..)` but creates a non-literal variable.

**Comment by tszirr** [comment]
Thanks, it might alleviate a few cases. However, my original case was with frequently changing literals coming out of scalar computations and being put into device variables. In this case, it still seems that `make_opaque` is the most robust and general solution at this point. (Concretely, my original issues arose in the frame loop of an interactive viewer that I had quickly slapped together in python/nanogui, where every time I moved the camera a new kernel was generated each frame.)
