### ISSUE TITLE
drjit.make_opaque fails with ad tensor

### ISSUE THREAD

**Issue by JamesZFS** [mitsuba-renderer/drjit#65]
I am trying to make an ad tensor type opaque:
```python
import drjit as dr
from drjit.llvm.ad import TensorXf

t = dr.zeros(TensorXf, (10, 10, 3))
dr.make_opaque(t)
```
Got `AttributeError: 'drjit.cuda.ad.TensorXf' object has no attribute 'detach_ref_'`

However, for non-ad tensors, it works fine

**Comment by Speierers** [comment]
Hi @JamesZFS,

Thanks for reporting this issue. It will be fixed in the next release: [f6bde89](https://github.com/mitsuba-renderer/drjit/commit/f6bde8920f352f8ea96e652034662e3513a59c45)
