### ISSUE TITLE
How to do enoki.psum() in drjit

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/drjit#68]
Here is an example I am trying to do for a discrete distribution:

```
using FloatC    = CUDAArray<float>;
m_pmf = ....
m_cmf = psum(m_pmf);
```

I see mitsuba3 was using a loop to calculate the cmf. Is Drjit cannot support Enoki's psum feature?
Let me know if there is any better way to calculate the cdf using drjit on gpu.
Thanks!

**Comment by Speierers** [comment]
Hi @andyyankai ,

Dr.Jit does not support the `psum` operation unfortunately. And this will likely never be supported given the high lane intricacy of such operation.

I suggest you "migrate" your buffer to the CPU and perform the computation there (see how it is done [here](https://github.com/mitsuba-renderer/mitsuba3/blob/b88c2d5202ef34939e0814ba5dde064a7114cb72/include/mitsuba/core/distr_1d.h#L53)
