### ISSUE TITLE
Concatenation of tensors

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#71]
Is there a way to concatenate multiple `TensorXf` objects, similar to `torch.cat`?

**Comment by Speierers** [comment]
No currently Dr.Jit doesn't provide such a function. Although this shouldn't be to hard to implement using `dr.gather` and `dr.scatter` calls. If you give this a try, please submit a PR, I will be happy to assist you to get it pushed onto the `master` branch.
