### ISSUE TITLE
More than 4 billion variables error

### ISSUE THREAD

**Issue by TZZZZ** [mitsuba-renderer/drjit#75]
Hi! I did a large optimization using Mitsuba and after many iterations received 

> 'Critical Dr.Jit compiler failure: DrJit has created more than 2^32 (4 billion) variables, which is currently the limit. Bug Wenzel to fix this (it will involve sorting scheduled variables by scope ID instead of variable ID and making the counter big enough that it will never overflow..)'. 

Could you please tell if this is fine / will be fixed / ... ?

**Comment by Speierers** [comment]
We are well aware of this issue al but unfortunately this won't be fixed in the near future.

**Comment by TZZZZ** [comment]
Ok, thank you for the answer.

**Comment by mfischer-ucl** [comment]
@Speierers 
would it help to call 
```python
dr.traverse(dr.cuda.ad.Float, dr.ADMode.Forward, dr.ADFlag.Default)
dr.traverse(dr.cuda.ad.Float, dr.ADMode.Backward, dr.ADFlag.Default)
```
after every few optimization steps? I encountered the same error, just trying this to see whether it will have any effects.

**Comment by Speierers** [comment]
No this won't make any difference as it won't reduce the number of variables handled by Dr.Jit.
