### ISSUE TITLE
[Question] Is there a way to concatenate two Dr.Jit arrays in python?

### ISSUE THREAD

**Issue by uguuuuuu** [mitsuba-renderer/drjit#79]
Is there a way to concatenate two arrays in python like `a = dr.concat(b, c)` where `a`, `b`, and `c` are Dr.Jit arrays of the same type, for example, `Vector3f`?
The only way I can think of is to convert them to, for example, a numpy array, concatenate them, and then convert the resulting array back into a Dr.Jit array. Is there a better way?

**Comment by Speierers** [comment]
Hi @uguuuuuu ,

Currently you have two options to concatenate Dr.Jit arrays in Python:
1. Go through `numpy` as you already suggested, although this will have some performance implications and you will loose the ability to differentiate through this operation
2. Use `dr.scatter` to construct the concatenated array as follow:

```python
m =  dr.llvm.ad

a = m.Float(...)
b = m.Float(...)

def concat(a, b):
        size_a = dr.width(a)
        size_b = dr.width(b)
        c = dr.empty(m.Float, size_a + size_b)
        dr.scatter(c, a, dr.arange(m.UInt32, size_a))
        dr.scatter(c, a, size_a + dr.arange(m.UInt32, size_b))
```

In the (untested) code above, I only concatenate flat arrays. In order for this to work, simply repeat this operation for all static entries of the `Vector3f` array:

```python
v = Vector3f(...)
output = Vector3f()
for i in len(v): 
    output[i] = concat(v[i])
```

Let me know if this works for you.

(untested code)

**Comment by uguuuuuu** [comment]
That definitely worked for me. Thank you so much!
