### ISSUE TITLE
How to shuffle a Tensor

### ISSUE THREAD

**Issue by DoeringChristian** [mitsuba-renderer/drjit#81]
Hi,
I have rendered a scene using an aov integrator, with normals as an output. This in my case returns a tensor of the shape: (256, 256, 6).
Now I want to get just the normal output from the 6 channels, do do so I tried using the ```dr.shuffle([2, 0, 1], aov)``` function.
Unfortunately this fails with the following error:
```
Traceback (most recent call last):
  File "/home/doeringc/workspace/python/mitsuba3/test-denoise.py", line 19, in <module>
    img = dr.shuffle([2, 0, 1], aov)
  File "/home/doeringc/workspace/cpp/mitsuba3-main/build/python/drjit/router.py", line 3196, in shuffle
    raise Exception("shuffle(): incompatible input!")
drjit.Exception: shuffle(): incompatible input!
```
When looking at the [implementation of shuffle](https://github.com/mitsuba-renderer/drjit/blob/805f4cef644e55935e8e55228e2b8f224fdc054b/drjit/router.py#L3178) I noticed, that ```len(perm)``` has to be equal to ```value.Size```.
```aov.Size``` in my case is: 18446744073709551615.

Example code
```python
import matplotlib.pyplot as plt
import mitsuba as mi
import drjit as dr
mi.set_variant("cuda_rgb")

scene = mi.cornell_box()
print(f"{scene=}")
scene['integrator'] = {
    'type': 'aov',
    'aovs': 'nn:sh_normal',
}
scene = mi.load_dict(scene)

aov = mi.render(scene)

print(f"{aov.Size=}")
print(f"{aov=}")

img = dr.shuffle([2, 0, 1], aov)
```

How can I shuffle this tensor to get the channels of my output, alternatively
is there another way to get only the normal channels without shuffling the tensor? 
Would you recommend using ```dr.gather```?

Thanks for your help.

**Comment by DoeringChristian** [comment]
I have found out how to get the normals:
The ```__getitem__``` function can take multiple slices as input. 
Therefore ```aov[:, :, 3:6]``` returns the normals from the tensor.
Should this be added to the documentation?
Shuffling a tensor would still be useful in other circumstances so I won't close the issue.

**Comment by Speierers** [comment]
Indeed the currently implementation of `dr.shuffle` doesn't work properly with `TensorXf`. You should use the `__getitem__` method instead for now as suggested by @DoeringChristian.

**Comment by Speierers** [comment]
Actually I looked more into this and it only really make sense for `dr.shuffle()` to work with "static" arrays (e.g. `Array3f`) where one wants to permute its dimensions. For `TensorXf` we recommend to use the `__getitem__()` method for those kind of operations. Another option is to convert a `TensorXf` into a static array using `dr.unravel()` and then use the `dr.shuffle()` function.
