### ISSUE TITLE
The location of cached kernel

### ISSUE THREAD

**Issue by holmes969** [mitsuba-renderer/drjit#83]
Hi,

I am wondering where I can find the cached kernels on the disk. Is it possible to delete cached kernels or redirect the stored location? Are the cached kernels stored as PTX files or even lower-level machine code?

Cheng

**Comment by wjakob** [comment]
They are in ``~/.drjit`` on Linux and macOS, and ``~/AppData/Local/Temp/drjit`` on Windows.

The cache files store either textual PTX/LLVM IR (depending on the backend) as long with the resulting machine code in binary form. The main goal for these files is to avoid a costly compilation step, and they must store both inputs and outputs of that step to do that. The IR data can be very big/redundant, and the files are therefore compressed with lz4.
