### ISSUE TITLE
Bug: tensor multi index broadcasting fails.

### ISSUE THREAD

**Issue by Jerry-Shen0527** [mitsuba-renderer/drjit#85]
I tried to do multi index tensor broadcasting and the indices go out of range. I went through the unit tests and found only single index broadcasting, so I guess multi index tensor broadcasting has not been tested.

![image](https://user-images.githubusercontent.com/47278074/194262217-598ec0c3-3149-4243-81fb-1a40cc77ca99.png)

I'm currently adding `else` before `size = size_next` in file tensor.h and this temporarily solves the problem.

**Comment by Speierers** [comment]
Hi, 

To better understand your issue, could you please provide a simple reproducer code?

**Comment by Jerry-Shen0527** [comment]
I tried to print out the indices used by gather in `tensor_broadcast_impl()` and in such multi indexed cases, some of the indices would go out of bounds.

I don't know whether this means I should not do multi indexed broadcasting, or it's just a miscalculation of the index.

**Comment by Speierers** [comment]
Hi @Jerry-Shen0527, indeed multiple-index broadcasting is likely not properly supported in Dr.Jit. It would be great to at least throw an exception when such a case is detected.

I will add this on our TODO list. For now I would recommend you stick with single index broadcasting or implement a fix yourself (in which case a PR would be greatly appreciated).

**Comment by njroussel** [comment]
Fixed with #146
