### ISSUE TITLE
An issue with dr.repeat and dr.tile

### ISSUE THREAD

**Issue by mariasoroka** [mitsuba-renderer/drjit#86]
As the title suggests, I am encountering some issues with dr.repeat and dr.tile.

The following fails with an error ``` AttributeError: module 'drjit.llvm.ad' has no attribute 'UInt8' ```
```
import drjit as dr
import mitsuba as mi
mi.set_variant('llvm_ad_rgb')

b = mi.Bool([True, False])
dr.repeat(b, 2)
```

The error message is the same for dr.tile.

**Comment by Speierers** [comment]
Thanks for reporting this. This is now fixed [c15a71d](https://github.com/mitsuba-renderer/drjit/commit/c15a71d4cf439fe239e1b6713fc426c6d94c45b7)
