### ISSUE TITLE
How to convert tensor to python builtin type?

### ISSUE THREAD

**Issue by kimren227** [mitsuba-renderer/drjit#94]
Hi,

I'm trying to convert a drjit.cuda.ad.Float to python builtin float. I've tried calling the .Scalar(), however, it always return 0.
```
some_var = dr.cuda.Float(1)
print(a) # [1.0]
print(some_var.Scalar()) # 0.0
```
What should be the correct way to do this?

Best Regards,
Daxuan

**Comment by njroussel** [comment]
Dr.Jit types are vectorized types, they kind of behave like arrays. So you could actually have `some_var = dr.cuda.Float(1, 2, 3)`, where `some_var` has multiple values.
In your example, if you're just using a single value, you should just lookup the first index: `some_var[0]`
