### ISSUE TITLE
question: feasibility of separating vectorization into separate library

### ISSUE THREAD

**Issue by samuelpmish** [mitsuba-renderer/drjit#97]
Hi, I've got a C++ code that I'm modifying to vectorize with enoki, and I've been really impressed with the speedups and how straightforward it is to adopt. I noticed that development on enoki has slowed, in favor of drjit-- which sounds like an amazing project! 

My question is: would it make sense to separate out the vectorization tools of these libraries (e.g. `enoki::Array` and its implementations for different SIMD instructions) into a separate repo? The ease of use and features (vectorization of special functions, masked operations, etc) make `enoki/drjit`'s vectorization capability way nicer than other SIMD libraries available, and making it into an independent module could help make it more accessible.

Thanks again for developing and sharing these wonderful libraries-- `drjit` seems like an incredibly ambitious project.

**Comment by wjakob** [comment]
Hi @samuelpmish,

in principle, Dr.Jit should completely subsume Enoki in the sense that the whole `enoki::Array<>` parts continue to work as a header-only library. Dr.Jit contains various extra bits like autodiff, just-in-time compilation, but all of this can be ignored by simply not compiling the library parts and not including the headers related to those features. 

With regards to splitting up the project into submodules: as you mention, Dr.Jit is an ambitious project, and we are pursuing it with a relatively small team. That unfortunately tends to imply that we don't have the time to pursue features or development that aren't directly motivated by research done by my group.

Cheers,
Wenzel

**Comment by samuelpmish** [comment]
Sounds great, I'll switch my project over to target drjit's vectorization tools going forward.

**Comment by wjakob** [comment]
Be sure to include the `<drjit/packet.h>` header and let us know if you have any issues. The ARM neon bits haven't been ported yet, there is a separate PR about this (#70)
